version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - URL=${URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"