version: '3.8'

services:
  # Node.js app
  app:
    build:
      context: .
    ports:
      - "3000:3000"  # Expose Node.js app to port 3000 on host
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379 
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    networks:
      - app-network  # Redis is only accessible by 'app' service inside the network

networks:
  app-network:
    driver: bridge
