version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://expressdb_owner:npg_iZkmzy2KXsr4@ep-misty-sound-a1n2iavn-pooler.ap-southeast-1.aws.neon.tech/expressdb?sslmode=require
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"